### PR TITLE
Use constexpr instead of const for float initialization

### PR DESCRIPTION
**Pull request by olekw**
Ensure compliance with C++11, and consistency with C++11 used elsewhere in the codebase.

### CODE REVIEW

**Comment by erikogenvik** [comment]
Have you verified that this works on the latest version of MSVC?
The reason we had to revert this change previously was because of MSVC support. See e7bf8e8ac8d2801ff70dcb1658c36e7002e60144

**Comment by olekw** [comment]
I don't have the means to verify that. The latest version is SUPPOSED to be compliant with C++11...

I CAN verify that without this change Mercator won't build correctly with gcc under C++11 rules; and without C++11 in Mercator, Cyphesis will not build in GCC5... :-\ (There is currently a release-critical bug against it in Debian)


On October 25, 2015 3:06:04 AM CDT, Erik Ogenvik <notifications@github.com> wrote:
>Have you verified that this works on the latest version of MSVC?
>The reason we had to revert this change previously was because of MSVC
>support. See e7bf8e8ac8d2801ff70dcb1658c36e7002e60144
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/worldforge/mercator/pull/3#issuecomment-150899633

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by erikogenvik** [comment]
Ok. Visual Studio 2015, which has been released, claims to have support for constexpr.
As this is a show stopper on Debian currently I'll merge it, and work under the assumption that it correctly compiles on Visual Studio 2015.

**Comment by erikogenvik** [comment]
This doesn't compile, so I had to undo the merge.

**Comment by erikogenvik** [comment]
This patch was incomplete and didn't compile. I instead reverted e7bf8e8ac8d2801ff70dcb1658c36e7002e60144.

**Comment by olekw** [comment]
Sorry about that! Strange though, it compiled ok in my Debian development environment...

Thanks for reverting that other commit. That'll do the trick and it seems a more comprehensive solution!

On October 25, 2015 9:31:58 AM CDT, Erik Ogenvik <notifications@github.com> wrote:
>This patch was incomplete and didn't compile. I instead reverted
>e7bf8e8ac8d2801ff70dcb1658c36e7002e60144.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/worldforge/mercator/pull/3#issuecomment-150928248

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
